[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[context.production]
  environment = { NEXT_TELEMETRY_DISABLED = "1" }

[context.deploy-preview]
  environment = { NEXT_TELEMETRY_DISABLED = "1" }

[[headers]]
  for = "/"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"